# Generated by Django 4.0.4 on 2022-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('bio', models.CharField(max_length=100000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('plot', models.CharField(max_length=100000)),
                ('kind', models.Field(choices=[('Tragádie', 'tragédie'), ('Epika', 'epika'), ('Lyrica', 'lyrica')])),
                ('genre', models.Field(choices=[('Drama', 'drama'), ('Komedie', 'komedie'), ('Roman', 'román'), ('Novela', 'novela'), ('Povídka', 'povídka'), ('Fejeton', 'fejeton'), ('Romaneto', 'romaneto'), ('Pohádka', 'pohádka'), ('Mýtus', 'mýtus'), ('Esej', 'esej'), ('Science fiction', 'sci-fi'), ('Fantasy', 'román'), ('Venkovskou prózu', 'venkovská próza'), ('Literaturu faktu', 'literatura faktu'), ('Detektivní román', 'detektivní román')])),
                ('publication_year', models.DateTimeField()),
                ('pages', models.IntegerField()),
                ('author', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
