# Generated by Django 4.0.4 on 2022-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_remove_book_genre_remove_book_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pages', 'name']},
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(help_text='Select genre', to='books.genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='kinds',
            field=models.ManyToManyField(to='books.kind'),
        ),
    ]
